### ISSUE TITLE
GCCXML_EXECUTABLE

### ISSUE THREAD

**Issue by alexnatch** [gccxml/gccxml#10]
Hello everyone,

I am trying to use gccxml to generate XML files but when I launc gccxml from the command line I have this error: Could not determine GCCXML_EXECUTABLE setting.

I don't know how to set this setting.

Coudl anyone tell me how to set it ?

Regards,

Alexandre.

**Comment by bradking** [comment]
The setting is normally automatic.  How did you build gccxml?  What top-level source directory did you use?

**Comment by alexnatch** [comment]
I took the source from github.

I then build gccxml using Cmake and Microsoft Visual Studio 2010.

I checked the config file:

GCCXML_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/cl.exe"
GCCXML_CXXFLAGS=" /DWIN32 /D_WINDOWS /W3 /GR /EHsc"

**Comment by bradking** [comment]
To what directory did you point CMake as the top-level source?  If only the `GCC_XML` subdirectory was built then this may happen.

**Comment by alexnatch** [comment]
I think it was to the GCC_XML subdirectory ? Do I have to build The whole directory ?

**Comment by bradking** [comment]
Yes, you need to build everything from the top.  Note that gccxml does not support VS >= 10.  It has been succeded by CastXML for that.

**Comment by alexnatch** [comment]
Yes I know but I have problems building CastXML so I turned to GCCXML
