### ISSUE TITLE
Add Visual Studio 2015/MSVC14 support

### ISSUE THREAD

**Issue by andrasfuchs** [gccxml/gccxml#13]
It's been 6.5 years since the last supported Visual Studio was released. It's really hard to get a MSVC10 compiler, since it can't easily be installed on a Windows 10 machine.

This commit summarizes the places where the changes should be made to support the newer versions: https://github.com/gccxml/gccxml/commit/d958e62bdd3df26c87c7317a9c1802ffb997b649

I have the MSVC 11, 12 and 14 installed on my computer, so I can help with the implementation and testing, just let me know what information is needed to make it happen.

The version numbers of the different Visual Studios are described here:
https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#History

**Comment by iMichka** [comment]
Hi

GCC-XML has been succeeded by CastXML (https://github.com/CastXML/CastXML).

There will be no more changes to GCC-XML (see bug #12  where somebody asked support for VS 2012 and 2013).

CastXML support the newest compilers and provides the same output format than GCCXML.

**Comment by andrasfuchs** [comment]
That's great, thank you! 

Could you please make a small note about the VS support and the drop-in replacement on the opening page of GCC-XML (https://github.com/gccxml/gccxml). 
It would have saved a few hours of work for me, if I knew this before. (I've also started to make a patch for MSVC 12 and 14.)

I was following a VTK guide and it was not updated, it still referred to GCC-XML instead of CastXML.

**Comment by iMichka** [comment]
There is a note on the opening page. But it is probably not prominent enough.
I'll leave that to @BradKing.

The VTK guide should be updated too (though I was not aware that VTK used GCC-XML: were you thinking about ITK?). Where did you find the guide?

**Comment by andrasfuchs** [comment]
I double checked, and I was not precise enough: GCC-XML is needed for the ActiViz.NET, the .NET wrapper of VTK, not VTK itself.

Sorry, I've spent a few days with these builds, and I remembered wrong where I was stuck last time.

The tutorial is very old, and can be found here: 
http://www.vtk.org/Wiki/VTK/CSharp/ActiViz/Build#XML_output_extension_to_the_C.2B.2B_front-end_of_GCC 
and there is another short description here: referring to gccxml:
http://www.kitware.com/opensource/avdownload.php

The most recent ActiViz source can be cloned from this GIT repo:
git://public.kitware.com/activizdotnet.git

**Comment by bradking** [comment]
Closing because GCC-XML is no longer maintained.

I've made commit dcd36c5c16a82511d5d25c6759678357726751d2 to make the link to CastXML more prominent.
