### ISSUE TITLE
Visual C directories are not in the repo

### ISSUE THREAD

**Issue by andrasfuchs** [gccxml/gccxml#14]
GCC_XML looks for support directories for every compiler. Without them the GCC_XML can't support a specific compiler. These files are located in https://github.com/gccxml/gccxml/tree/master/GCC_XML/Support by default.

This repo doesn't contain the files for any of the MSVC compilers. VC9 is supported in code, but can't be used since the directory Support/Vc9 is not there.

If those files ever existed, please upload check them in to make the Visual C compilation possible again.

**Comment by iMichka** [comment]
Hi. The answer is the same as in #13, there will probably be no more changes to GCCXML, and you should try to use CastXML, which is a drop-in replacement.
