### ISSUE TITLE
Wrong output for typedef of anonymous structs

### ISSUE THREAD

**Issue by ceving** [gccxml/gccxml#15]
I have the following C source `typedef_anonymous_struct.c`:

    typedef struct {
      int car;
      int cdr;
    } pair_t;

I convert it to XML by this command:

    $ gccxml typedef_anonymous_struct.c -fxml=typedef_anonymous_struct.xml

In the output I expect a `Struct` node with no name and a `Typedef` node with a name. But GCCXML generates a `Struct` with a name:

    $ echo $(xmllint --format --xpath '//Struct[@name="pair_t"]' typedef_anonymous_struct.xml)
    <Struct id="_75" name="pair_t" context="_1" mangled="6pair_t" demangled="pair_t" location="f1:4" file="f1" line="4" size="64" align="32" members="_159 _160 _161 _162 _163 _164 " bases=""/>

And no `Typdef` at all:

    $ echo $(xmllint --format --xpath '//Typedef[@name="pair_t"]' typedef_anonymous_struct.xml)
    XPath set is empty

This are two bugs. The `Struct` must not have a name and the `Typedef` is missing.

**Comment by bradking** [comment]
GCC-XML is no longer maintained.  It has been superseded by [CastXML](https://github.com/CastXML/CastXML).  CastXML supports C (which GCC-XML never did), and produces the proper output for the example shown.
