### ISSUE TITLE
the gccxml/GCC cmake configuration under cygwin: returns "Configuration x86_64-unknown-cygwin not supported"

### ISSUE THREAD

**Issue by ptizoom** [gccxml/gccxml#16]
after a... 
 mkdir bld
 cd bld
 cmake ..

I get...
...
-- Checking for struct tms
-- Checking for struct tms - found
-- Checking for clock_t
-- Checking for clock_t - found
running /usr/bin/sh.exe "/usr/src/openairinterface5g/dependencies/gccxml/GCC/config_cmake/gcc_platform.sh" "/usr/src/openairinterface5g/dependencies/gccxml/bld/GCC/config_cmake/gcc_platform.cmake" "/usr/bin/cmake.exe"  2>&1
*** Configuration x86_64-unknown-cygwin not supported
CMake Error at GCC/config_cmake/CMakeLists.txt:724 (MESSAGE):
  Cannot find
  '/usr/src/openairinterface5g/dependencies/gccxml/bld/GCC/config_cmake/gcc_platform.cmake'
....

I think the GNU config.guess and config.sub, configure
need to be refreshed, is there a nice ibride way to do just that with autoreconf ?

thx.

**Comment by ptizoom** [comment]
well, I added around line 1107 of gccxml/GCC/gcc/config.gcc the following case...
"... 
x86_64-*-cygwin*)
	#PTZ181130
	tm_file="${tm_file} i386/unix.h i386/bsd.h i386/gas.h dbxcoff.h i386/cygming.h i386/cygwin.h i386/x86-64.h"
	xm_file=i386/xm-cygwin.h
	tmake_file="i386/t-cygwin i386/t-cygming"
	target_gtfiles="\$(srcdir)/config/i386/winnt.c"
	extra_options="${extra_options} i386/cygming.opt"
	extra_objs="winnt.o winnt-stubs.o"
	c_target_objs=cygwin2.o
	cxx_target_objs="cygwin2.o winnt-cxx.o"
	extra_gcc_objs=cygwin1.o
	if test x$enable_threads = xyes; then
		thread_file='posix'
	fi
	;;

..."


compilation should follow (after a minor change in toplevel.h) . but it coughs at link time.
partly again with this many definition of floor_log2() and libc_name_p!

tbc...

**Comment by iMichka** [comment]
Hi. You should consider using https://github.com/CastXML/CastXML. Gccxml is deprecated.
