### ISSUE TITLE
 relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC

### ISSUE THREAD

**Issue by longbowlee** [gccxml/gccxml#17]

**Comment by longbowlee** [comment]
issue fixed by
export CFLAGS="-fPIC" && cmake ../gccxml -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/bin

**Comment by bradking** [comment]
gccxml is no longer maintained.  Please use [CastXML](https://github.com/CastXML/CastXML) instead.
